version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: [ "./main" ]

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: [ "go", "test", "./..." ]
    depends_on:
      - postgres
